# === Stage 53: Add command help text and usage examples ===
# Project: CourseForge
def help_text():
    """Display usage instructions and examples for CourseForge CLI."""
    print("=" * 60)
    print("CourseForge - Collaborative Course Builder")
    print("=" * 60)
    print("\nUsage:")
    print("  python courseforge.py <command> [options]")
    print()
    print("Commands:")
    print("  init                    Initialize a new course project")
    print("  add-module <name>       Add a new module to the course")
    print("  add-lesson <module>     Create a lesson within an existing module")
    print("  add-exercise <lesson>   Attach an exercise to a specific lesson")
    print("  review                   Display all reviews across lessons")
    print("  progress                 Show current learner progress summary")
    print()
    print("Examples:")
    print('  python courseforge.py init')
    print('  python courseforge.py add-module "Introduction to Python"')
    print('  python courseforge.py add-lesson "Getting Started" --module "Introduction to Python"')
    print('  python courseforge.py add-exercise "Your First Script" --lesson "Getting Started"')
    print("  python courseforge.py review")
    print("  python courseforge.py progress")
    print()
    print("Tips:")
    print("  - Use descriptive names for modules and lessons.")
    print("  - Add exercises to reinforce key concepts in each lesson.")
    print("  - Check reviews regularly to track learner feedback.")
    print("=" * 60)
